import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { createDb } from "../db/db";
import { useState, useEffect } from "react";

const Home: NextPage = () => {
  const [items, setItems] = useState([]);
  useEffect(() => {
    (async () => {
      const db = await createDb(1);

      const res = await db.heroes
        .find({
          selector: {},
        })
        .exec();

      setItems(res.map((doc) => doc.toJSON()));
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Items after migration: <br /> {JSON.stringify(items)}
      </main>
    </div>
  );
};

export default Home;
